name: Change Plugin Name

on:
  workflow_dispatch:
    inputs:
      oldPluginName:
        description: 'Old Plugin Name'
        type: string
        required: true
        default: 'PLUGIN_NAME'
      newPluginName:
        description: 'New Plugin Name'
        type: string
        required: true
        default: 'PLUGIN_NAME'

permissions:
  contents: write

jobs:
  run:

    runs-on: ubuntu-latest
    env:
      WORKFLOWS_DIRECTORY: .github/workflows
      SCRIPTS_DIRECTORY: .github/workflows/scripts
      OLD_PLUGIN_NAME: ${{ inputs.oldPluginName }}
      NEW_PLUGIN_NAME: ${{ inputs.newPluginName }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ${{ env.SCRIPTS_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python Script
      run: python $SCRIPTS_DIRECTORY/change_plugin_name.py