name: Change Plugin Name

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'E4-Unreal/project-workflows'
      newPluginName:
        description: 'New Plugin Name'
        type: string
        required: true
        default: 'PLUGIN_NAME'

permissions:
  contents: write

jobs:
  run:

    runs-on: ubuntu-latest
    env:
      WORKFLOWS_DIRECTORY: .github/workflows
      SCRIPTS_DIRECTORY: .github/workflows/scripts/change_plugin_name
      NEW_PLUGIN_NAME: ${{ inputs.newPluginName }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: ${{ inputs.repository }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ${{ env.SCRIPTS_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python scripts
      run: python $SCRIPTS_DIRECTORY/main.py
    - name: Push commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Chore: 플러그인 이름 수정 ($NEW_PLUGIN_NAME)"
        git push
