name: Change Plugin Name

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository'
        required: true
        default: 'E4-Unreal/project-workflows'
      newPluginName:
        description: 'New Plugin Name'
        type: string
        required: true
        default: 'PLUGIN_NAME'

permissions:
  contents: write

jobs:
  change-plugin-name:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TARGET_REPOSITORY_PATH }}
    env:
      WORKFLOWS_REPOSITORY_PATH: workflows-repository
      TARGET_REPOSITORY_PATH: target-repository
      WORKFLOWS_DIRECTORY: .github/workflows
      SCRIPTS_DIRECTORY: .github/workflows/scripts/change_plugin_name
      NEW_PLUGIN_NAME: ${{ inputs.newPluginName }}

    steps:
    - name: Checkout Workflows Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: ${{ env.WORKFLOWS_REPOSITORY_PATH }}
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: ${{ env.TARGET_REPOSITORY_PATH }}
        token: ${{ secrets.CONTENTS_READ_WRITE }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ${{ env.WORKFLOWS_REPOSITORY_PATH }}/${{ env.SCRIPTS_DIRECTORY }}
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run python scripts
      run: python ../${{ env.WORKFLOWS_REPOSITORY_PATH }}/${{ env.SCRIPTS_DIRECTORY }}/main.py
    - name: Push commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Chore: 플러그인 이름 수정 ($NEW_PLUGIN_NAME)"
        git push
